/*View the Menu**: Write a query to select all columns from the `menu_items` table.*/
SELECT *
 FROM menu_items;
 /*Italian Dishes**: Display the `item_name` and `price` of all items in the 'Italian' category.*/
 SELECT item_name, price
 FROM menu_items
WHERE category ='ITALIAN';
/*Cheap Eats**: Find all menu items with a price less than $10.00 */
SELECT item_name, price
FROM menu_items 
WHERE price < 10.00;
/*Count the Dishes**: How many unique menu items are there in the table?*/
SELECT count(DISTINCT item_name)
FROM menu_items;
/*Orders on a Date**: How many orders were placed on '2023-01-01'? (Hint: Count the rows in `order_details`)*/
SELECT count(*)
FROM order_details
WHERE order_date = '2023-01-01';
/*Sort by Price**: List all menu items sorted by price in descending order.*/
SELECT *
FROM menu_items
ORDER by price DESC;
/*Null Check**: Are there any orders in `order_details` that have a missing `item_id`?*/
SELECT item_id
FROM order_details
WHERE item_id IS NULL;
/* Item Popularity**: What is the total number of orders for each menu item? Display the `item_name` and the count of orders.*/
SELECT mi.item_name, COUNT(*) 
AS order_count
FROM order_details od
JOIN menu_items mi
  ON od.item_id = mi.item_id
GROUP BY mi.item_name;
/*Category Revenues**: Calculate the total revenue generated by each `category` (e.g., Italian, Mexican).*/
SELECT mi.category, SUM(mi.price) total_revenue
FROM order_details od
JOIN menu_items mi
  ON od.item_id = mi.item_id
GROUP BY mi.category;
/*Order Sizes**: What is the average number of items per order? (Hint: You need to group by `order_id` first)*/
SELECT AVG(item_count) AS avg_items_per_order
FROM (
  SELECT order_id, COUNT(*) item_count
  FROM order_details
  GROUP BY order_id
)  order_counts;
/*Top Spenders**: Which order (`order_id`) had the highest total price?*/
SELECT od.order_id, SUM(mi.price) total_price
FROM order_details od
JOIN menu_items mi
  ON od.item_id = mi.item_id        
GROUP BY od.order_id
ORDER BY total_price DESC
LIMIT 1;
/*Daily Trends**: How many orders were placed each day? List the date and the count.*/
SELECT order_date, COUNT(*) 
AS daily_order_count
FROM order_details
GROUP BY order_date
ORDER BY order_date;
/*Hourly Rush**: At what hour of the day do most orders occur?*/
SELECT EXTRACT(HOUR FROM order_time) hour_of_day, COUNT(*) AS order_count
FROM order_details
GROUP BY EXTRACT(HOUR FROM order_time)
ORDER BY order_count DESC
LIMIT 1;
/*Pricey Categories**: What is the average price of items in each category?*/
SELECT category, AVG(price) AS avg_price
FROM menu_items
GROUP BY category;
/*Cumulative Revenue**: Calculate the running total of revenue for each day in January 2023.*/
SELECT order_date, SUM(SUM(mi.price)) OVER (ORDER BY order_date) cumulative_revenue
FROM order_details od
JOIN menu_items mi 
ON od.item_id = mi.item_id
WHERE order_date 
BETWEEN '2023-01-01' AND '2023-01-31'
GROUP BY order_date;\
/*Category Growth**: For each category, calculate the month-over-month growth rate in revenue.*/
WITH monthly_revenue AS (
    SELECT mi.category,
    DATE_TRUNC(order_date, MONTH) AS revenue_month,
    SUM(mi.price) AS total_revenue
    FROM order_details od
    JOIN menu_items mi
    ON od.item_id = mi.item_id
    GROUP BY mi.category, DATE_TRUNC(order_date, MONTH)
)
SELECT category, revenue_month, total_revenue,
    LAG(total_revenue) OVER (PARTITION BY category ORDER by revenue_month) AS previous_month_revenue,
    CASE 
        WHEN LAG(total_revenue) OVER (PARTITION BY category ORDER by revenue_month) IS NULL THEN NULL 
        ELSE (total_revenue - LAG(total_revenue) OVER (PARTITION BY category ORDER by revenue_month))
    /LAG(total_revenue) OVER (PARTITION BY category ORDER by revenue_month) * 100
    END AS month_over_month_growth_rate
FROM monthly_revenue
ORDER BY category, revenue_month;
/*Top 3 Per Category**: Using a window function, find the top 3 most ordered items within each category.*/
SELECT 
    category,
    item_name,
    order_count
FROM (
    SELECT 
        mi.category,
        mi.item_name,
        COUNT(*) AS order_count,
        DENSE_RANK() OVER (
            PARTITION BY mi.category
            ORDER BY COUNT(*) DESC
        ) AS rank_in_category
    FROM order_details od
    JOIN menu_items mi
        ON od.item_id = mi.item_id
    GROUP BY mi.category, mi.item_name
) ranked_items
WHERE rank_in_category <= 3
ORDER BY category, order_count DESC;
/*High Value Customers**: Identify orders that spent more than the average order value.*/
SELECT
    order_id,
    order_total
FROM (
    SELECT
        od.order_id,
        SUM(mi.price) AS order_total
    FROM order_details od
    JOIN menu_items mi
        ON od.item_id = mi.item_id
    GROUP BY od.order_id
) order_totals
WHERE order_total >
(
    SELECT AVG(order_total)
    FROM (
        SELECT
            od.order_id,
            SUM(mi.price) AS order_total
        FROM order_details od
        JOIN menu_items mi
            ON od.item_id = mi.item_id
        GROUP BY od.order_id
    ) avg_table
);
/*Menu Optimization**: Which menu items have never been ordered?*/
SELECT mi.menu_item_id, mi.item_name
FROM menu_items mi
LEFT JOIN order_details od 
ON mi.menu_item_id = od.item_id
WHERE od.item_id IS NULL;
/*Weekend vs. Weekday**: Compare the average daily revenue between weekends (Saturday/Sunday) and weekdays*/
WITH daily_revenue AS (
    SELECT 
        order_date,
        SUM(mi.price) AS total_revenue,
        CASE 
            WHEN EXTRACT(DOW FROM order_date) IN (0, 6) THEN 'Weekend'
            ELSE 'Weekday'
        END AS day_type
    FROM order_details od
    JOIN menu_items mi
        ON od.item_id = mi.item_id
    GROUP BY order_date
)
SELECT 
    day_type,
    AVG(total_revenue) AS avg_daily_revenue
FROM daily_revenue
GROUP BY day_type;  
/*Customer retention(proxy)**:Find the distribution of order sizes (number of items per order)*/
SELECT item_count, COUNT(*) AS order_count
FROM (
    SELECT order_id, COUNT(*) AS item_count
    FROM order_details
    GROUP BY order_id
) order_sizes
GROUP BY item_count
ORDER BY item_count;
